twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        ra_domain: '%env(RA_DOMAIN)%'
        game_path: '%gamePath%'
        badge_path: '%badgePath%'
        console_path: '%consolePath%'